### ISSUE TITLE
차단 풀어줘요

### ISSUE THREAD

**Issue by Fireworks1205** [noamboy2006/dissolveAPI#3]
~~그냥 장난이었는데 이걸 진짜 차단하네~~
디코 막히니까 말할 방법이 여기밖에 없었네요.
아이 뭐 장난인데 뭐
라떼는 마리야 어 그랬다가는 확!
목숨이 날라갔어어
요즘이니까 안그러지 어?!
몇년 전이었어도 내가 확! 혼쭐을 내줬을텐데 기분이 좋으니 이번만 봐준다~
이마리야
알겠지?
그러니까 빨리 차단 푸러

**Comment by Fireworks1205** [comment]
재송합니다 귀엽고 창의적이고 똑똑한 디솔브님

**Comment by noamboy2006** [comment]
이쉑
